title:  འཛུགས་བསྐྲུན་རྣམ་གྲངས་ཀྱི་ཐད་ལ་སྤེལ་བའི་ལས་འགུལ།
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: ''
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: མདུན་ངོས
   url: /index.html


social:
   github: Gyangmig
   twitter: Gyangmig
   facebook: Gyangmig
   email: gyangmig@gmail.com

google_analytics: " "
